---
- name: Ensure tools directory exists
  file:
   path: "{{tools_dir}}"
   state: directory
   mode: 0755
   owner: "{{ ansible_user_id }}"
   group: "{{ ansible_user_id }}"

- name: Ensure prerequisites are installed
  apt:
    name:
      - "python3"
      - "python3-pip"
      - "python3-virtualenv"
      - "git"
    state: present
    update_cache: true
  become: yes

- name: Clone Pacu repository
  git:
    repo: https://github.com/RhinoSecurityLabs/pacu.git
    dest: "{{tools_dir}}/pacu"
    accept_hostkey: yes
    force: yes
    version: HEAD

- name: Install pacu pip requirements
  pip:
    requirements: "{{tools_dir}}/pacu/requirements.txt"
    virtualenv: "{{tools_dir}}/pacu/venv"