- name: Ensure prerequisites are installed
  apt:
    name: 
      - "python3"
      - "python3-pip"
      - "python3-virtualenv"
      - "git"
    state: present
    update_cache: yes

- name: Clone sandcastle repository
  git:
    repo: https://github.com/Parasimpaticki/sandcastle.git
    dest: "{{tools_dir}}/sandcastle"
    accept_hostkey: yes
    force: yes
    version: HEAD
