---
- name: Ensure python3 and pip are installed
  apt:
    name: [python3, python3-dev, python3-pip]
    state: present
  become: yes

- name: Install TruffleHog
  pip:
    name: truffleHog
    state: present
  become: yes