---
dependency:
  name: galaxy
driver:
  name: docker
lint:  ansible-lint -x 401,305
platforms:
  - name: instance
    image: kalilinux/kali-linux-docker:latest
provisioner:
  name: ansible
verifier:
  name: testinfra
