# https://github.com/darkbitio/aws-recon
---
- name: Install ruby and gem
  apt:
    name: ruby-full
    state: present
    update_cache: true
  become: true

- name: install aws_recon
  gem:
    name: aws_recon
    state: present
  become: yes
