---
- name: Install python3, pip3
  apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes

- name: Install checkov
  pip:
    name: checkov
    state: present
    executable: pip3