# https://github.com/accurics/terrascan

- name: Download and unpack terrascan
  ansible.builtin.unarchive:
    src: https://github.com/accurics/terrascan/releases/download/v{{ terrascan_version }}/terrascan_{{ terrascan_version }}_Linux_x86_64.tar.gz
    dest: "/usr/bin/"
    remote_src: yes
  become: true
