- name: Ensure git, Python, and pip are installed
  apt:
    name: ['git', 'python', 'python-pip']
    state: present

- name: Clone cloudjack repository
  git:
    repo: https://github.com/prevade/cloudjack.git
    dest: "{{ tools_dir }}/cloudjack"
    accept_hostkey: yes
    force: yes
    version: HEAD

- name: Install cloudjack pip requirements
  pip:
    name: boto3
    state: present

