- name: Ensure Python 3 and pip3 are installed
  apt:
    name: 
      - "python3"
      - "python3-pip"
      - "python3-virtualenv"
      - "git"
    state: present
    update_cache: yes
  become: true

- name: Clone PMapper repository
  git:
    repo: https://github.com/nccgroup/PMapper.git
    dest: "{{tools_dir}}/pmapper"
    accept_hostkey: yes
    force: yes
    version: HEAD

- name: Install PMapper pip requirements
  pip:
    requirements: "{{tools_dir}}/pmapper/requirements.txt"
    virtualenv: "{{tools_dir}}/pmapper/venv"
