
---
- name: Install MSDAT apt requirements
  apt:
    name: ["freetds-dev", "python-pip", "git"]
    state: present
  become: "yes"

- name: Install MSDAT pip requirements
  pip:
    name: ["cython", "colorlog", "termcolor", "pymssql", "argparse", "argcomplete"]
    state: "present"

- name: Clone MSDAT repository
  git:
    repo: "https://github.com/quentinhardy/msdat.git"
    dest: "{{ tools_dir }}/msdat"
    version: "master"
