---
- name: Ensure tools directory exists
  file:
   path: "{{tools_dir}}"
   state: directory
   mode: 0755
   owner: "{{ ansible_user_id }}"
   group: "{{ ansible_user_id }}"
  become: true

- name: Ensure cloudmapper apt dependencies are installed
  apt:
    name: 
      - "git"
      - "python3"
      - "python3-pip"
      - "python3-virtualenv"
      - "autoconf"
      - "automake"
      - "libtool"
      - "python3-dev"
      - "python3-tk"
      - "jq"
      - "python3-distutils"
      - "python3-apt"
      - "libfreetype-dev"
      - "libfreetype6-dev"
      - "libfreetype6"
      - "pkg-config"
      - "libpng-dev"
    state: present
    update_cache: yes
  become: yes

- name: Clone cloudmapper repository
  git:
    repo: https://github.com/duo-labs/cloudmapper.git
    dest: "{{tools_dir}}/cloudmapper"
    accept_hostkey: yes
    force: yes
    version: HEAD

- name: Install cloudmapper pip requirements
  pip:
    requirements: "{{tools_dir}}/cloudmapper/requirements.txt"
    virtualenv: "{{tools_dir}}/cloudmapper/venv"
