---

- name: Ensure tools directory exists
  file:
   path: "{{tools_dir}}"
   state: directory
   mode: 0755
   owner: "{{ ansible_user_id }}"
   group: "{{ ansible_user_id }}"

- name: Install prerequisites
  apt:
    name: ["git", "python3",'python3-tk', "python3-dev", "python3-pip", "python3-virtualenv"]
    state: present
    update_cache: yes
  become: yes

- name: Clone aws-inventory repository
  git:
    repo: https://github.com/nccgroup/aws-inventory.git
    dest: "{{tools_dir}}/aws-inventory"
    accept_hostkey: yes
    force: yes
    version: HEAD

- name: Install aws-inventory pip requirements
  pip:
    requirements: "{{tools_dir}}/aws-inventory/requirements.txt"
    virtualenv: "{{tools_dir}}/aws-inventory/venv"