- name: Ensure Python 2 and pip are installed
  apt:
    name: ['python', 'python3', 'python-pip', 'python3-pip', 'git']
    state: present

- name: Install the AWS CLI
  pip:
    name: awscli
    state: present
    executable: pip3

- name: Clone Prowler repository
  git:
    repo: https://github.com/toniblyx/prowler.git
    dest: "{{ tools_dir }}/prowler"
    accept_hostkey: yes
    force: yes
    version: HEAD