# https://github.com/duo-labs/parliament
---
- name: Install prerequisites
  apt:
    name: 
      - "git"
      - "python3"
      - "python3-dev"
      - "python3-pip"
      - "python3-virtualenv"
    state: present
    update_cache: yes
  become: yes

- name: Install the parliament pip packages
  pip:
    name: ['parliament']
    state: present
    executable: pip3