---
- name: Ensure tools directory exists
  file:
   path: "{{tools_dir}}"
   state: directory
   mode: 0755
   owner: "{{ ansible_user_id }}"
   group: "{{ ansible_user_id }}"

- name: Install prerequisites
  apt:
    name:
      - gnupg
      - ca-certificates
      - apt-transport-https
      - git
      - python3
      - python3-dev
      - python3-pip
      - python3-virtualenv
    state: present
    update_cache: true
  become: yes

- name: Clone gcp-iam-collector repository
  git:
    repo: https://github.com/marcin-kolda/gcp-iam-collector.git
    dest: "{{tools_dir}}/gcp-iam-collector"
    accept_hostkey: yes
    force: yes
    version: HEAD

- name: Install gcp-iam-collector pip requirements
  pip:
    requirements: "{{tools_dir}}/gcp-iam-collector/requirements.txt"
    virtualenv: "{{tools_dir}}/gcp-iam-collector/venv"