- name: Ensure tools directory exists
  file:
   path: "{{tools_dir}}"
   state: directory
   mode: 0755

- name: Install prerequisites
  apt:
    name: 
      - "git"
      - "python3"
      - "python3-dev"
      - "python3-pip"
      - "python3-virtualenv"
    state: present
    update_cache: yes
  become: yes

- name: Clone aws_pwn repository
  git:
    repo: https://github.com/dagrz/aws_pwn.git
    dest: "{{tools_dir}}/aws_pwn"
    accept_hostkey: yes
    force: yes
    version: HEAD

- name: Install aws_pwn pip requirements
  pip:
    requirements: "{{tools_dir}}/aws_pwn/requirements.txt"
    virtualenv: "{{tools_dir}}/aws_pwn/venv"